project: dot
providers:
  google_secrets_manager:
    kind: google_secretmanager
    maps:
      - id: secrets
        path: projects/vfarcic
        keys:
          github-cosign: COSIGN_PRIVATE_KEY
          cosign-password: COSIGN_PASSWORD
          github-token: GITHUB_TOKEN
          github-org: GITHUB_USER
