---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "name" . }}
    spec:
      containers:
      - name: main
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        {{- if .Values.db.enabled }}
        env: 
        - name: DB_ENDPOINT
          value: {{ template "name" . }}-postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "name" . }}-postgresql
              key: postgres-password
        - name: DB_NAME
          value: silly-demo
        {{- end }}