storage:
  type: memory
provisionDataStore:
  cassandra: false
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
allInOne:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - jaeger.34.138.210.209.nip.io
