storage:
  type: none
provisionDataStore:
  cassandra: false
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
allInOne:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - jaeger.127.0.0.1.nip.io
