values:
  ingress:
    className: nginx
    host: silly-demo.127.0.0.1.nip.io
  autoscaling:
    enabled: true
    minReplicas: 1
  db:
    enabled: true
    provider: "cnpg"
    schema: |
      create table videos (
        id varchar(50) not null,
        title text,
        primary key (id)
      );
      create table comments (
        id serial,
        video_id varchar(50) not null,
        description text not null,
        primary key (id),
        CONSTRAINT fk_videos FOREIGN KEY(video_id) REFERENCES videos(id)
      );
  otel:
    enabled: true
    jaegerAddr: http://jaeger-collector.monitoring:4318
