// Code generated by timoni. DO NOT EDIT.
// Note that this file must have no imports and all values must be concrete.

package main

values: {
	image: tag: "1.4.49"
	// ingress: {
	// 	className: "traefik"
	// 	host: "sillydemo.127.0.0.1.nip.io"
	// }
	// autoscaling: enabled: true
	// db: enabled: trued
}
