name: pr
run-name: pr
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build-container-image:
    runs-on: ubuntu-latest
    env:
      TAG: 1.4.${{ github.run_number }}
      FORCE_COLOR: 1
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-qemu
        uses: docker/setup-qemu-action@v3
      - name: login-to-ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: vfarcic
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: install-devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          project-path: devbox-ci.json
      - name: run-unit-tests
        run: devbox run --config devbox-ci.json -- ./dot.nu run unit_tests
      - name: build-image
        run: devbox run --config devbox-ci.json -- ./dot.nu build image pr-${{ github.event.number }}
        env:
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      - name: deploy-app
        run: devbox run --config devbox-ci.json -- ./dot.nu deploy app
      - name: run-integration-tests
        run: devbox run --config devbox-ci.json -- ./dot.nu run integration_tests
